### ISSUE TITLE
Non-Interactive Deployment

### ISSUE THREAD

**Issue by heywoodlh** [khast3x/Redcloud#7]
First off, thanks for a great project.

I'm working on Ansible playbooks to deploy Redcloud. Is there a way to deploy Redcloud on a remote machine without requiring user interaction? Not using the menu, but rather supplying all the configuration via a config file or arguments to `redcloud.py`.

My desired workflow is to non-interactively `git clone` the repository and run `python redcloud.py`/installing without a dialog.

Anyway, any suggestions would be great!

**Comment by khast3x** [comment]
Hello, thank you for checking Redcloud out. 
I have not yet planned when I will be adding new features to Redcloud, but arguments or config fold were part of the potential new feature. Is that what you had in mind? 
Cheers!

**Comment by heywoodlh** [comment]
Yep, some way to pass the configuration to RedCloud without requiring user interaction _just_ to get it running would be awesome (arguments or a config file). 

Btw, most of my fellow security analysts on my team and myself have been playing with RedCloud over the past few days and we think we'll probably add it to our pen-testing kit. It's a great tool!

**Comment by khast3x** [comment]
Oh wow what nice feedback to read, thanks! 
I'll keep this issue opened until I find the time to add this.
Cheers!

**Comment by heywoodlh** [comment]
Hey actually, I just decided to `docker-compose build` and `docker-compose up` the RedCloud installation and that worked perfectly fine. Here are the Ansible tasks for it (for the record):

```
---
- name: git clone https://github.com/khast3x/Redcloud.git /opt/redcloud
  git:
    repo: https://github.com/khast3x/Redcloud.git
    dest: /opt/redcloud
  become: true
- name: mkdir -p /opt/portainer/data
  file:
    path: /opt/portainer/data
    state: directory
  become: true
- name: docker-compose build && docker-compose up in /opt/redcloud
  docker_compose:
    build: yes
    project_src: /opt/redcloud/ 
  become: true
```




For my purposes running `docker-compose` is sufficient for what I need so if you want to close this issue you totally can.
